development:
  log_level: debug
  log_file_path: ./ele.log 
  src:
    data_file: ./ele.log
  dst:
    data_file: ./ele.txt

production:
  log_level: info
  log_file_path: ./ele.log
  src:
    data_file: ele.log
  dst:
    data_file: ./ele.txt
